name: Deploy API and App to Azure Container Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Stap 1: Checkout de code
    - name: Checkout code
      uses: actions/checkout@v3

    # Stap 2: Log in bij Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login slagboomacr.azurecr.io \
          -u ${{ secrets.ACR_USERNAME }} --password-stdin

    # Stap 3: DNS-labels genereren (vast of dynamisch)
    - name: Generate DNS Labels
      id: dns_labels
      run: |
        API_DNS_NAME="api-container-$RANDOM"
        APP_DNS_NAME="app-container-$RANDOM"
        echo "API_DNS_NAME=$API_DNS_NAME" >> $GITHUB_ENV
        echo "APP_DNS_NAME=$APP_DNS_NAME" >> $GITHUB_ENV
        echo "Generated DNS labels: $API_DNS_NAME and $APP_DNS_NAME"

    # Stap 4: Build en push de API-container
    - name: Build and Push API Container
      run: |
        docker build -t slagboomacr.azurecr.io/api-container:latest ./API_python
        docker push slagboomacr.azurecr.io/api-container:latest

    # Stap 5: Build en push de App-container
    - name: Build and Push App Container
      run: |
        docker build -t slagboomacr.azurecr.io/flask-app-container:latest ./App_python
        docker push slagboomacr.azurecr.io/flask-app-container:latest

    # Stap 6: Log in bij Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Stap 7: Debugging: Controleer secrets en omgevingsvariabelen
    - name: Debugging Secrets and Variables
      run: |
        echo "Resource Group: ${{ secrets.RESOURCE_GROUP }}"
        echo "API DNS: ${{ env.API_DNS_NAME }}"
        echo "APP DNS: ${{ env.APP_DNS_NAME }}"

    # Stap 8: Deploy API-container
    - name: Deploy API to Azure Container Instance
      run: |
        az container create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name api-container \
          --image slagboomacr.azurecr.io/api-container:latest \
          --registry-login-server slagboomacr.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --environment-variables API_KEY=${{ secrets.API_KEY }} VAR1=value1 VAR2=value2 \
          --cpu 1 \
          --memory 1.5 \
          --dns-name-label ${{ env.API_DNS_NAME }} \
          --ports 4000 \
          --os-type Linux

    # Stap 9: Deploy App-container
    - name: Deploy App to Azure Container Instance
      run: |
        az container create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name flask-app-container \
          --image slagboomacr.azurecr.io/flask-app-container:latest \
          --registry-login-server slagboomacr.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --environment-variables API_KEY=${{ secrets.API_KEY }} VAR1=value1 VAR2=value2 \
          --cpu 1 \
          --memory 1.5 \
          --dns-name-label ${{ env.APP_DNS_NAME }} \
          --ports 5000 \
          --os-type Linux

    # Stap 10: Verifieer de API-container deployment
    - name: Verify API Deployment
      run: |
        az container show \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name api-container --query "{status:instanceView.state, events:instanceView.events}" --output table

    # Stap 11: Verifieer de App-container deployment
    - name: Verify App Deployment
      run: |
        az container show \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name flask-app-container --query "{status:instanceView.state, events:instanceView.events}" --output table
