name: Deploy to Azure Container Instance

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io \
          -u ${{ secrets.ACR_USERNAME }} --password-stdin

    # Step 3: Build and Push the Container Image to ACR
    - name: Build and Push Container Image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}

    # Step 4: Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 5: Deploy the container to Azure Container Instance
    - name: Deploy container to Azure Container Instance
      run: |
        az container create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name ${{ secrets.ACI_NAME }} \
          --image ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} \
          --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --environment-variables VAR1=value1 VAR2=value2 \
          --cpu 1 \
          --memory 1.5 \
          --dns-name-label ${{ secrets.DNS_NAME }} \
          --ports 80 \
          --os-type Linux  # Explicitly set the OS type to Linux

    # Step 6: Add tags to the container
    - name: Add tags to container
      run: |
        az resource tag \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name ${{ secrets.ACI_NAME }} \
          --resource-type "Microsoft.ContainerInstance/containerGroups" \
          --tags CreatedBy=Omar

    # Step 7: Verify the deployment
    - name: Verify Deployment
      run: |
        az container show \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name ${{ secrets.ACI_NAME }}
