name: Deploy API and App to Azure Container Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Stap 1: Checkout de code
    - name: Checkout code
      uses: actions/checkout@v3

    # Stap 2: Debugging Secrets and Variables
    - name: Debug Resource Group
      run: echo "Resource Group: ${{ secrets.RESOURCE_GROUP }}"

    # Stap 3: Log in bij Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login slagboomacr.azurecr.io \
          -u ${{ secrets.ACR_USERNAME }} --password-stdin

    # Stap 4: Deploy API-container
    - name: Deploy API to Azure Container Instance
      run: |
        az container create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name api-container \
          --image slagboomacr.azurecr.io/api-container:latest \
          --registry-login-server slagboomacr.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --environment-variables API_KEY=${{ secrets.API_KEY }} VAR1=value1 VAR2=value2 \
          --cpu 1 \
          --memory 1.5 \
          --dns-name-label api-container \
          --ports 4000 \
          --os-type Linux
